baseURL = "https://tomimulhartono.github.io/"
title = "Tomi Mulhartono"
paginate = 13
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Tomi Mulhartono"
description = "Unlock the secrets of cybersecurity and programming in my chill portfolio blog! Join me on a journey where coding prowess meets digital defense. From coding hacks to cybersecurity strategies, discover it all in a relaxed vibe that makes learning fun!"
keywords = [
    "Cybersecurity",
    "Programming",
    "Web Security",
    "Ethical Hacking",
    "Software Development",
    "Coding Tips",
    "Cyber Defense",
    "Penetration Testing",
    "Network Security",
    "Programming Languages",
    "Cyber Threats",
    "Application Security",
    "Cyber Awareness",
    "Secure Coding",
    "Cybersecurity Tools"
]
author = "Tomi Mulhartono"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = false
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = true

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there👋"
  Content = "Welcome to my cybersecurity and programming portfolio blog! 💻🛡️ Enter a realm where lines of code serve as sentinels, guarding the digital landscape. Join me on this journey where innovation meets vigilance, and together, we'll navigate the ever-evolving world of technology. Let's embark on this adventure!"

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/tomimulhartono/"

  [[params.socialIcons]]
  name = "HackThebox"
  url = "https://app.hackthebox.com/profile/1825248"

  [[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/tomimulhartono"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

  [outputs]
  home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[markup.highlight]
noClasses = false

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[markup]
  [markup.tableOfContents]
    endLevel = 10
    ordered = false
    startLevel = 2